version: '3'
services:
  hubot:
    container_name: hubot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    env_file:
      - .env
    tty: true
    restart: always